### PR TITLE
Wait for pending ticks started by test

### LINKED ISSUE #994: Lab crash on simple test code
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v14.7.0
* *module version with issue*: 23.0.0
* *last module version without issue*: 
* *environment* (e.g. node, browser, native): native
* *used with* (e.g. hapi application, another framework, standalone, ...):
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

To run test suite without lab crashing. Eg. the following with `lab fail.js -i 1`:

fail.js:
```js
'use strict';

const Hoek = require('@hapi/hoek');
const Lab = require('@hapi/lab');


// Test shortcuts

const lab = exports.lab = Lab.script();
const { it } = lab;


it('does not crash lab', async () => {

    await Hoek.wait(1);

    process.nextTick(() => {

        throw new Error('fail');
    });
});

it('has another test', async () => {

});
```

#### What was the result you got?

  ```
  ./<snip>/fail.js:19
        throw new Error('fail');
        ^

Error: fail
    at /<snip>/fail.js:19:15
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

#### What result did you expect?

```

  
  .

1 tests complete
Test duration: 3 ms
Leaks: No issues
```

Note that lab doesn't crash when running the full suite, but it assigns the error to the second test.

This specific issue can probably be remedied by letting ticks settle before treating the test as "completed".

### PR DESCRIPTION
**Pull request by geek**
Fixes #994

### CODE REVIEW

File: lib/runner.js [hunk 1]
```diff
@@ -662,6 +662,11 @@ internals.protect = function (item, state) {
 
                 try {
                     await item.fn.call(null, flags);
+                    // wait for any pending ticks started by the test
+                    await new Promise((next) => {
+
+                        process.nextTick(next);
```
Comment (kanongil) [inline lib/runner.js:668]: This will work better with an `setImmediate()`, as it allows all ticks and promises to settle.

**Review by devinivy — APPROVED** [review]

**Review by kanongil — APPROVED** [review]
