### PR TITLE
Fail test if a falsy value is thrown by the test

### LINKED ISSUE #812: awaiting a rejected promise can still pass test
The following test "passes" in lab@15.2.2 when I would _not_ expect it to as it `awaits` a rejected promise
```JavaScript
it.only('lab should mark as fail, but doesn`t', async () => {

    let rejectP;
    const p = new Promise((resolve, reject) => {

        rejectP = reject;
    });
    setTimeout(rejectP, 5); // if I passed a param to rejectP the test would fail

    await p;

    console.log("never called - but test passes");
    throw new Error('This test should fail, but passes');
});
```
What happens is that `await p` results in an uncaught exception, but because `rejectP` was called with no parameter then all the checks like `if (err ` in the runner pass.

A quick hack for me would be to add the below `|| 'rejected'` to [lib/runner.js#L581](https://github.com/hapijs/lab/blob/master/lib/runner.js#L581)
```JavaScript
return finish(ex || 'rejected');
```

I am happy to prepare a PR if you are agreeable. Let me know.

### PR DESCRIPTION
**Pull request by rankida**
This fixes #812 _awaiting a rejected promise can still pass test_. All the info can be found here.

### CODE REVIEW

File: lib/runner.js [hunk 1]
```diff
@@ -578,7 +578,7 @@ internals.protect = function (item, state) {
                 finish();
             }
             catch (ex) {
-                return finish(ex);
+                return finish(ex || 'reject');
```
Comment (Marsup) [inline lib/runner.js]: Shouldn't it be a `new Error()` ?

Comment (rankida) [reply lib/runner.js]: If it is an `Error` then it will flow the full way through and report an empty string as the error, whereas setting it as a string results in the standard `Non Error object received or caught` message.

I am happy enough with either (my priority is that the test fail) so really depends on what feedback makes most sense

**with 'reject'**
```
Failed tests:

  27) Executor jobs throw:

      Non Error object received or caught

      at finish...
```

**with `new Error()`**
```
   27) Executor jobs throw:



      at Immediate.setImmediate...
```

Comment (geek) [reply lib/runner.js]: This seems reasonable to me, @Marsup any objections to the current implementation?

**Comment by ORESoftware** [comment]
maybe dis better?

```js
return finish(ex || 'dummy hapijs reject');
```

File: lib/runner.js (hunk 1 above)
Comment (Marsup) [reply lib/runner.js]: OK, didn't investigate enough to tell, I was just surprised that it could end with an error or a string. If you're happy I'm happy.

Comment (lerouxb) [reply lib/runner.js]: What's wrong with `new Error('Empty promise rejection.')`?

Comment (rankida) [reply lib/runner.js]: As I said above, the "problem" with using an genuine `Error` is that you follow the same path as any errors that come from the test.

So you could see the error message `'Empty promise rejection.'` and think your test was actually throwing that.

The reason I chose a non-`Error` value is that I think the existing message `Non Error object received or caught` is the most appropriate and fits in nicely with the existing behaviour.

That said, as long as it is set to _something_ I do not care too much. My priority is that it fails the test.

Comment (rankida) [reply lib/runner.js]: @geek if you want me to change anything just let me know

**Comment by rankida** [comment]
@ORESoftware thanks for your comment.

The string is used only internally to `lab` so I don't think it matters too much. If it does need changed I would prefer something that does not mention `hapi` as you might think this si something coming from the webserver.

I have addressed the comments about using `Error` in the thread above
